// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIb00NX6Vq1iQZiZf-GA2A5mJ-RrwNZAM',
    appId: '1:735176048829:web:5ed2428c538e54efc977d4',
    messagingSenderId: '735176048829',
    projectId: 'amst-flutter-db-72780',
    authDomain: 'amst-flutter-db-72780.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-72780-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72780.appspot.com',
    measurementId: 'G-4VP4GBMT0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbwv39G8vupWelPB6JjXk5MYiLPlimas',
    appId: '1:735176048829:android:a2871728d4dbf77cc977d4',
    messagingSenderId: '735176048829',
    projectId: 'amst-flutter-db-72780',
    databaseURL: 'https://amst-flutter-db-72780-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj20BS2lb6fSNJFAtFz74bCvMRr9pQVMc',
    appId: '1:735176048829:ios:42779da984fd1abac977d4',
    messagingSenderId: '735176048829',
    projectId: 'amst-flutter-db-72780',
    databaseURL: 'https://amst-flutter-db-72780-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72780.appspot.com',
    iosClientId: '735176048829-rbjjqkpdg39vf45nr2necdfkc0h1qdi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj20BS2lb6fSNJFAtFz74bCvMRr9pQVMc',
    appId: '1:735176048829:ios:a8097be623a154a6c977d4',
    messagingSenderId: '735176048829',
    projectId: 'amst-flutter-db-72780',
    databaseURL: 'https://amst-flutter-db-72780-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72780.appspot.com',
    iosClientId: '735176048829-1ik7oi748l311qch48iu4v4qt15bksse.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb.RunnerTests',
  );
}
